server:
  port: 8090

spring:
  application:
    name: feelmeal
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - db
      - openapi
      - jwt
    active: local
  servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 100MB
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: spring:session
    timeout: 3600 # 1시간


security:
  ignorePaths:
    - "/**"
  postIgnorePaths: []
  patchIgnorePaths: []
  getIgnorePaths: []