# application-local.yml
spring:
    config:
        activate:
            on-profile: local
openapi:
    service:
        title: feelmeal-documentation
        version: 1.0.0
        url: http://localhost:8090

springdoc:
    api-docs:
        path: /api/v3/api-docs
    swagger-ui:
        path: /api/swagger-ui.html
        operations-sorter: method
        doc-expansion: none
